(def v 3)
(def str "Something Wonderful!")
(def name "YoonJung")

(println v)
(println "1234")
(println (+ 2 3))
(println "Hello World!")
(println #\n)
(println (+ 2 5.2))
(println (* 2 (/ (- 3 2) 5.3)))
(println (+ v 10))
(println str)
(println (+ "a" "b"))

(println (+ (+ "Hello, " name) "!"))