(module ReadLine)

(import Module.map)
(import Module.split)
(import Module.to-string)
(import Module.filter)

(def line (read-line))
(println line)
(println (list line))
(def trimmed (to-string (filter (list line) (lambda (ch) (/= ch #\Space)))))
(println trimmed)
(def splitted (split trimmed #\,))
(println splitted)
(def nums (map (lambda (s) (int s)) splitted))
(def sum (fold nums 0 +))
(def avg (/ (double sum) (len nums)))

(println sum)
(println avg)
