package lengine;

import lengine.functions.LengineLambdaCommon;
import lengine.util.Nil;
import lengine.util.StreamNil;

public class Prelude {
  public static final LengineLambdaCommon ADD = PreludeImpl._ADD;
  public static final LengineLambdaCommon SUB = PreludeImpl._SUB;
  public static final LengineLambdaCommon MULT = PreludeImpl._MULT;
  public static final LengineLambdaCommon DIV = PreludeImpl._DIV;
  public static final LengineLambdaCommon REM = PreludeImpl._REM;
  public static final LengineLambdaCommon NORM = PreludeImpl._NORM;
  public static final LengineLambdaCommon LEN = PreludeImpl._LEN;
  public static final LengineLambdaCommon TAKE = PreludeImpl._TAKE;
  public static final LengineLambdaCommon DROP = PreludeImpl._DROP;
  public static final LengineLambdaCommon HEAD = PreludeImpl._HEAD;
  public static final LengineLambdaCommon TAIL = PreludeImpl._TAIL;
  public static final LengineLambdaCommon FOLD = PreludeImpl._FOLD;
  public static final LengineLambdaCommon LESS_THAN = PreludeImpl._LESS_THAN;
  public static final LengineLambdaCommon LESS_EQUALS = PreludeImpl._LESS_EQUALS;
  public static final LengineLambdaCommon GREATER_THAN = PreludeImpl._GREATER_THAN;
  public static final LengineLambdaCommon GREATER_EQUALS = PreludeImpl._GREATER_EQUALS;
  public static final LengineLambdaCommon EQUALS = PreludeImpl._EQUALS;
  public static final LengineLambdaCommon NOT_EQUALS = PreludeImpl._NOT_EQUALS;
  public static final LengineLambdaCommon AND = PreludeImpl._AND;
  public static final LengineLambdaCommon OR = PreludeImpl._OR;
  public static final LengineLambdaCommon NOT = PreludeImpl._NOT;
  public static final LengineLambdaCommon PRINTLN = PreludeImpl._PRINTLN;
  public static final LengineLambdaCommon PRINT = PreludeImpl._PRINT;
  public static final LengineLambdaCommon PRINTF = PreludeImpl._PRINTF;
  public static final LengineLambdaCommon FORMAT = PreludeImpl._FORMAT;
  public static final LengineLambdaCommon RANGE = PreludeImpl._RANGE;
  public static final LengineLambdaCommon INCLUSIVE_RANGE = PreludeImpl._INCLUSIVE_RANGE;
  public static final LengineLambdaCommon ASSERT = PreludeImpl._ASSERT_TRUE;
  public static final LengineLambdaCommon ASSERT_TRUE = PreludeImpl._ASSERT_TRUE;
  public static final LengineLambdaCommon ASSERT_FALSE = PreludeImpl._ASSERT_FALSE;
  public static final LengineLambdaCommon ASSERT_EQUALS = PreludeImpl._ASSERT_EQUALS;
  public static final LengineLambdaCommon ASSERT_NOT_EQUALS = PreludeImpl._ASSERT_NOT_EQUALS;
  public static final LengineLambdaCommon CAST_STR = PreludeImpl._CAST_STR;
  public static final LengineLambdaCommon CAST_INT = PreludeImpl._CAST_INT;
  public static final LengineLambdaCommon CAST_DOUBLE = PreludeImpl._CAST_DOUBLE;
  public static final LengineLambdaCommon CAST_CHARACTER = PreludeImpl._CAST_CHARACTER;
  public static final LengineLambdaCommon CAST_LIST = PreludeImpl._CAST_LIST;
  public static final LengineLambdaCommon CAST_SEQ = PreludeImpl._CAST_SEQ;
  public static final LengineLambdaCommon IS_BOOL = PreludeImpl._IS_BOOL;
  public static final LengineLambdaCommon IS_CHAR = PreludeImpl._IS_CHAR;
  public static final LengineLambdaCommon IS_INT = PreludeImpl._IS_INT;
  public static final LengineLambdaCommon IS_DOUBLE = PreludeImpl._IS_DOUBLE;
  public static final LengineLambdaCommon IS_STR = PreludeImpl._IS_STR;
  public static final LengineLambdaCommon IS_LIST = PreludeImpl._IS_LIST;
  public static final LengineLambdaCommon IS_SEQ = PreludeImpl._IS_SEQ;
  public static final LengineLambdaCommon IS_OBJECT = PreludeImpl._IS_OBJECT;
  public static final LengineLambdaCommon IS_CONS = PreludeImpl._IS_CONS;
  public static final LengineLambdaCommon IS_NIL = PreludeImpl._IS_NIL;
  public static final LengineLambdaCommon IS_STREAM_NIL = PreludeImpl._IS_STREAM_NIL;
  public static final LengineLambdaCommon IS_STREAM_CONS = PreludeImpl._IS_STREAM_CONS;
  public static final LengineLambdaCommon OPEN_FILE = PreludeImpl._OPEN_FILE;
  public static final LengineLambdaCommon NOW = PreludeImpl._NOW;
  public static final LengineLambdaCommon CONS = PreludeImpl._CONS;
  public static final LengineLambdaCommon STREAM_CONS = PreludeImpl._STREAM_CONS;
  public static final LengineLambdaCommon KEY = PreludeImpl._KEY;
  public static final LengineLambdaCommon KEYS = PreludeImpl._KEYS;
  public static final LengineLambdaCommon ENTRY = PreludeImpl._ENTRY;
  public static final LengineLambdaCommon ENTRIES = PreludeImpl._ENTRIES;
  public static final LengineLambdaCommon GET = PreludeImpl._GET;
  public static final LengineLambdaCommon READ_LINE = PreludeImpl._READ_LINE;
  public static final LengineLambdaCommon READ_EOF = PreludeImpl._READ_EOF;
  public static final LengineLambdaCommon READ_FILE = PreludeImpl._READ_FILE;
  public static final LengineLambdaCommon READ_FILE_SEQ = PreludeImpl._READ_FILE_SEQ;
  public static final LengineLambdaCommon APPEND_ITEM = PreludeImpl._APPEND_ITEM;
  public static final LengineLambdaCommon IS_SET = PreludeImpl._IS_SET;
  public static final LengineLambdaCommon GET_NIL = PreludeImpl._GET_NIL;
  public static final LengineLambdaCommon CAST_SET = PreludeImpl._CAST_SET;
  public static final LengineLambdaCommon DOES_HAVE = PreludeImpl._DOES_HAVE;
  public static final LengineLambdaCommon MERGE = PreludeImpl._MERGE;
  public static final LengineLambdaCommon ASYNC = PreludeImpl._ASYNC;
  public static final LengineLambdaCommon AWAIT = PreludeImpl._AWAIT;
  public static final LengineLambdaCommon WAIT = PreludeImpl._WAIT;
  public static final LengineLambdaCommon CHANNEL = PreludeImpl._CHANNEL;
  public static final LengineLambdaCommon SEND = PreludeImpl._SEND;
  public static final LengineLambdaCommon RECEIVE = PreludeImpl._RECEIVE;
  public static final LengineLambdaCommon CLOSE = PreludeImpl._CLOSE;
  public static final LengineLambdaCommon LISTEN = PreludeImpl._LISTEN;
  public static final LengineLambdaCommon HELP = PreludeImpl._HELP;
  public static final LengineLambdaCommon HELP_KEYWORD = PreludeImpl._HELP_KEYWORD;
  public static final LengineLambdaCommon DB_CONN = PreludeImpl._DB_CONN;
  public static final Object NIL = Nil.get();
  public static final Object STREAM_NIL = StreamNil.get();

}
